### ISSUE TITLE
kissmetrics doesn't fire kissmetrics default pageview events

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-kissmetrics#1]
_From @reinpk on June 27, 2014 14:46_

https://github.com/segmentio/analytics.js-integrations/blob/master/lib/kissmetrics/index.js#L65

should call `.page()` rather than `.trackPage()`, otherwise the default pageview doesn't get generated at all (here I have to manually trigger it from the console on our own site):
https://cloudup.com/cX6Q4dbQ4U2

our kissmetrics account shows no default pageviews either, and a helpful user pointed out that they're not seeing them either

_Copied from original issue: segmentio/analytics.js-integrations#250_

**Comment by ndhoule** [comment]
_From @reinpk on June 27, 2014 15:14_

@DirtyAnalytics is there a reason we don't do this now? are we trying to avoid pageview calls?

**Comment by ndhoule** [comment]
_From @ianstormtaylor on June 27, 2014 16:5_

For this one, there are basically two types of pageviews:
1. the unnamed `Page View` event that KISSmetrics _can_ record automatically, but doesn't record automatically by default, to save people event volume.
2. the named events we send, like `Viewed Home Page`, that are unrelated to KISSmetrics, but super useful for funnels and such.

I think the named ones should be fine.

The unnamed ones, will only be tracked if you enable them in your KISSmetrics settings. I think our account has them disabled (this is the default) and that user's probably does too. In general though I think those unnamed pageviews aren't super useful for KM, since they jack up the price a lot I guess, but we should document this behavior.

Let me know if that doesn't make any sense at all.

**Comment by ndhoule** [comment]
_From @DirtyAnalytics on June 27, 2014 16:29_

Ah yes...

![screen shot 2014-06-27 at 9 25 25 am](https://cloud.githubusercontent.com/assets/5532776/3414598/c41c3c7e-fe17-11e3-9b30-ee0b556cc5ce.png)

I can add to docs so people can enable in KISSmetrics if they want. 

@reinpk for our own instance of KISSmetrics we are using the KISSmetrics default "Visited Site" which fires when people first hit the site, and we also have named page calls for all of our pages as far as I know.

**Comment by ndhoule** [comment]
_From @jparker165 on June 27, 2014 20:50_

This is really a fault in KissMetrics.

In the current KM product, the named events are needed in order to see 'Metrics' for a specific pageview or use specific pageviews as funnel steps. The unnamed pageviews are needed in order to see total pageview counts -- which I personally use a proxy for user engagement.

The named events are definitely more important and should be the default. And I would not choose to eliminate these events in order to see total pageview counts. Though I would elect to send the the unnamed event **as well**. However this is clearly cost-prohibitive and going to create maintenance problems.

Anyone have a friend on the KissMetrics product team and can convince them to fix this on their side? -- making named pageviews also increment the total unnamed pageview counter.

**Comment by ndhoule** [comment]
_From @ianstormtaylor on June 27, 2014 21:42_

I don't think there's a fault anywhere. If we turned on the `Page View`
event in KISSmetrics, our integration would send both named and unnamed.
It's just because we have it off that we aren't sending it.

**Comment by ndhoule** [comment]
_From @chuckjliu on June 27, 2014 23:58_

Hi guys - Chuck from KISSmetrics here.

`Page View` is just like any other named event you can track - but we just do it for you.

Since `Page View` is considered a separate event completely (it really is just another named event), it doesn't make sense to increment an actual named event like `Viewed Homepage` to `Page View`. Both events would trigger at the same time if you had `Page View` turned on.

As @ianstormtaylor mentions, it acts similarly to `Visited Site` in that you can turn it on/off as you please.

**Comment by hankim813** [comment]
closed for inactivity/irrelevance
