### ISSUE TITLE
Completed Order event doesn't include a Billing Amount property

### ISSUE THREAD

**Issue by oboxodo** [segment-integrations/analytics.js-integration-kissmetrics#12]
I was tracking "Completed Order" from the client side with analytics.js, sending the `revenue` property, but I noted Segment wasn't "translating" that into KM's "expected" (configurable, but still) `Billing Amount` property.

I changed to start tracking the same event from my server using your analytics-ruby gem, sending exactly the same properties and then the `Billing Amount` property started being sent correctly to KISSmetrics.

Here you have proof from KM's live view:

![KISSmetrics showing Completed Order from JS and Ruby](https://www.evernote.com/l/AXVtKTdOw7tGbIpJC4k3pxE4PjehkuVjZLAB/image.png)

So I conclude your JS integration has some bug. Right?

**Comment by sperand-io** [comment]
Thanks! 

Billing Amount fix: https://github.com/segment-integrations/analytics.js-integration-kissmetrics/blob/master/lib/index.js#L136-L141

@hankim813 mind doing a review of how we're sending product data and figuring out how to move forward there?

**Comment by hankim813** [comment]
@sperand-io yeah there's a jira ticket for this https://segment.atlassian.net/browse/INT-176

We should do this next sprint for sure

**Comment by oboxodo** [comment]
So... has a fix for this been released? I understand you use Jira to track it so this ticket might been outdated here?

**Comment by oboxodo** [comment]
Hey Kissmetrics, can you confirm if you have deployed a fix for this already or not?

**Comment by hankim813** [comment]
@oboxodo hey sorry for the long wait -- I opened a PR #20 to fix the two issues here. 

Going to deploy Tuesday since Monday is a holiday and since Friday we have code freezes

**Comment by hankim813** [comment]
@oboxodo deployed! let me know if you still have issues!
